name: serverpod_offline_sync_benchmark
description: Local CRDT vs baseline performance impact measurement.
publish_to: none

environment:
  sdk: '^3.10.3'

resolution: workspace

dependencies:
  benchmark_harness: ^2.4.0
  intl: ^0.20.2
  path: ^1.9.1
  serverpod_database: 3.5.0-beta.9
  serverpod_offline_sync_server:
    path: ../packages/serverpod_offline_sync_server
  serverpod_offline_sync_shared:
    path: ../packages/serverpod_offline_sync_shared
  serverpod_offline_sync_test_client:
    path: ../test/serverpod_offline_sync_test_client

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
