name: serverpod_offline_sync_benchmark
description: Local CRDT vs baseline performance impact measurement.
publish_to: none

environment:
  sdk: '^3.12.2'

resolution: workspace

dependencies:
  args: ^2.7.0
  crypto: ^3.0.7
  benchmark_harness: ^2.4.0
  intl: ^0.20.2
  path: ^1.9.1
  serverpod: ^4.1.0-beta.3
  serverpod_auth_core_server: ^4.1.0-beta.3
  serverpod_database: ^4.1.0-beta.3
  serverpod_offline_sync:
    path: ../packages/serverpod_offline_sync
  serverpod_offline_sync_client:
    path: ../packages/serverpod_offline_sync_client
  serverpod_offline_sync_server:
    path: ../packages/serverpod_offline_sync_server
  serverpod_offline_sync_test_client:
    path: ../test/serverpod_offline_sync_test_client
  serverpod_offline_sync_test_server:
    path: ../test/serverpod_offline_sync_test_server

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_cli: ^4.1.0-beta.3
  test: ^1.25.5
