name: serverpod_offline_sync
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - packages/serverpod_offline_sync_client
  - packages/serverpod_offline_sync_server
  - packages/serverpod_offline_sync_shared
  - test/serverpod_offline_sync_test_client
  - test/serverpod_offline_sync_test_server

# dependency_overrides:
#   serverpod:
#     git:
#       url: https://github.com/serverpod/serverpod.git
#       path: packages/serverpod
#       ref: main
#   serverpod_client:
#     git:
#       url: https://github.com/serverpod/serverpod.git
#       path: packages/serverpod_client
#       ref: main
#   serverpod_database:
#     git:
#       url: https://github.com/serverpod/serverpod.git
#       path: packages/serverpod_database
#       ref: main
#   serverpod_shared:
#     git:
#       url: https://github.com/serverpod/serverpod.git
#       path: packages/serverpod_shared
#       ref: main
#   serverpod_serialization:
#     git:
#       url: https://github.com/serverpod/serverpod.git
#       path: packages/serverpod_serialization
#       ref: main
#   serverpod_test:
#     git:
#       url: https://github.com/serverpod/serverpod.git
#       path: packages/serverpod_test
#       ref: main
