name: drift_offline_sync
description: A Drift plugin to build offline-first applications with CRDT support.
version: 4.0.0-beta.0
repository: https://github.com/marcelomendoncasoares/drift_offline_sync

environment:
  sdk: ^3.8.0

# TODO: Relax the package constraints to expand compatibility.
dependencies:
  clock: ^1.1.2
  drift: ^2.28.0
  meta: ^1.12.0
  uuid: ^4.5.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  build_runner: ^2.6.0
  cli_tools: ^0.10.0
  drift_dev: ^2.28.0
  intl: ^0.20.2
  lints: ^6.0.0
  path: ^1.9.1
  sqlite3: any
  test: ^1.26.2
  test_descriptor: ^2.0.2
