import 'package:drift/drift.dart' hide isNotNull, isNull;
import 'package:drift_offline_sync/drift_offline_sync.dart';
import 'package:drift_offline_sync/src/hlc/normalized.dart';
import 'package:test/test.dart';

import '../utils/crdt_context.dart';
import '../utils/database.dart';
import '../utils/tables.dart';

void main() {
  group('Given a data object with every column type', () {
    late CrdtDatabase crdtDb;
    late TableWithEveryColumnTypeData createdData;
    late Hlc testHlc;

    setUp(() async {
      createdData = _createTestData();
      (_, crdtDb, _) = database.crdtContext;
      testHlc = Hlc.now(crdtDb.nodeId);
    });

    group('when converting the data to CRDT data entries', () {
      late Iterable<CrdtDataEntry> entries;

      setUp(() async {
        entries = crdtDb.convertToCrdtDataEntry(createdData, testHlc);
      });

      test('then it creates an entry for each column.', () async {
        // Get column names from entries (requires async lookups)
        final columnNames = <String>{};
        for (final entry in entries) {
          final column = await (crdtDb.select(crdtDb.crdtSchemaColumnsTable)
                ..where((t) => t.id.equals(entry.columnId)))
              .getSingle();
          columnNames.add(column.columnName);
        }
        expect(
          columnNames,
          equals(
            database.tableWithEveryColumnType.$columns.map((c) => c.$name).toSet(),
          ),
        );
      });

      test('then each entry has the correct user ID.', () async {
        expect(entries.map((e) => e.userId), everyElement(equals(crdtDb.userId)));
      });

      test('then each entry has the correct table name.', () async {
        // Get table name from first entry
        final firstEntry = entries.first;
        final table = await (crdtDb.select(crdtDb.crdtSchemaTablesTable)
              ..where((t) => t.id.equals(firstEntry.tableId)))
            .getSingle();
        expect(
          table.tblName,
          equals('table_with_every_column_type'),
        );
      });

      test('then each entry has the correct HLC timestamp.', () async {
        // Check HLC components match
        final expectedDatetime = NormalizedHlc.extractDatetime(testHlc);
        final expectedCounter = NormalizedHlc.extractCounter(testHlc);
        expect(
          entries.map((e) => e.hlcDatetime),
          everyElement(equals(expectedDatetime)),
        );
        expect(
          entries.map((e) => e.hlcCounter),
          everyElement(equals(expectedCounter)),
        );
      });

      test('then all entries have expected column names and values.', () async {
        final mappedData = await database.tableWithEveryColumnType.fromCrdtDataEntries(
          entries,
          crdtDb,
        );
        expect(mappedData.single, equals(createdData));
      });
    });
  });

  group('Given a changeset converted from a data object with every column type', () {
    late OfflineSyncCrdt crdt;
    late CrdtDatabase crdtDb;
    late TableWithEveryColumnTypeData createdData;
    late List<CrdtDataEntry> expectedChangeset;
    late Hlc testHlc;

    setUp(() async {
      createdData = _createTestData();
      (crdt, crdtDb, _) = database.crdtContext;

      // Perform an insert to the database to get the exact changeset that would
      // be generated by the CRDT triggers.
      await database.tableWithEveryColumnType.insertOne(createdData);
      expectedChangeset = await crdtDb.managers.crdtDataTable
          .filter(
            (f) {
              final isDeletedColumnId = crdtDb.schemaCache.getColumnId(
                f.tableId.peek()!,
                crdtDb.sqlBuilder.isDeletedColumnName,
              );
              return f.columnId.equals(isDeletedColumnId).not();
            },
          )
          .get();
      // Reconstruct HLC from first entry
      final firstEntry = expectedChangeset.first;
      final node = await (crdtDb.select(crdtDb.crdtNodesTable)
            ..where((t) => t.id.equals(firstEntry.hlcNodeId)))
          .getSingle();
      testHlc = NormalizedHlc.reconstruct(
        datetime: firstEntry.hlcDatetime,
        counter: firstEntry.hlcCounter,
        nodeId: node.nodeId,
      );
      await crdtDb.crdtDataTable.deleteAll();
    });

    group('when saving the changeset to the CRDT database', () {
      late Iterable<CrdtDataEntry> entries;

      setUp(() async {
        entries = crdtDb.convertToCrdtDataEntry(createdData, testHlc);
        await crdt.saveChangeset(entries, [testHlc]);
      });

      test('then the saved data is equal to the generated by CRDT triggers.', () async {
        final savedChangeset = await crdtDb.managers.crdtDataTable.get();

        // The list object is not equal to the other objects because it is a
        // different instance. So we remove it from the list and compare the
        // it separately.
        final savedListObject = savedChangeset.removeAt(7);
        final expectedListObject = expectedChangeset.removeAt(7);

        expect(savedChangeset, equals(expectedChangeset));
        expect(
          savedListObject.unwrappedValue,
          equals(expectedListObject.unwrappedValue),
        );
      });
    });
  });
}

TableWithEveryColumnTypeData _createTestData() => TableWithEveryColumnTypeData(
  id: const RowId(1),
  aBool: true,
  aDateTime: DateTime.now(),
  aText: 'test',
  anInt: 1,
  anInt64: BigInt.one,
  aReal: 1.0,
  aBlob: Uint8List.fromList([1, 2, 3]),
  anIntEnum: TodoStatus.open,
  aTextWithConverter: MyCustomObject('test'),
  aUuid: UuidValue.fromString('123e4567-e89b-12d3-a456-426614174000'),
);
