/// AUTOGENERATED BY SERVERPOD create-migration - DO NOT EDIT BY HAND
/// Merging: resolve registry conflicts the same as migration_registry.txt.
library;

import 'package:serverpod_database/serverpod_database.dart';

part '20260703114649226/migration.dart';
part '20260824213459360/migration.dart';
part '20260831202219662/migration.dart';
part '20260901174859443/migration.dart';

/// Migration registry for the client-side database.
class MigrationRegistry {
  /// Ordered list of all client-side database migrations.
  /// New migrations are always appended at the end.
  static final List<MigrationVersionSql> migrations = [
    _Migration20260703114649226(),
    _Migration20260824213459360(),
    _Migration20260831202219662(),
    _Migration20260901174859443(),
  ];

  /// List of all client-side database migration versions.
  static List<String> get versions => migrations.map((m) => m.version).toList();
}
