name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable-*
  pull_request:
    branches:
      - main
      - stable-*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  dart_format:
    name: dart format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run pub get
        run: dart pub get
      # Skip code generation for formatting check
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  dart_analyze:
    name: dart analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run pub get
        run: dart pub get
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run lint
        run: dart analyze .

  tests:
    name: dart test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run pub get
        run: dart pub get
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run tests
        run: dart test

  benchmarks:
    name: run benchmarks
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run pub get
        run: dart pub get
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run benchmarks
        run: dart benchmarks/run.dart --ci > benchmark-results.txt
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: benchmark-results.txt
          comment-tag: benchmark-results

  publish_check:
    name: dart publish check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run pub get
        run: dart pub get
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run publish dry run
        run: dart pub publish --dry-run
